sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t iainlr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true iainlr/docker-react npm run test
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-123123123123"
#   bucket_path: "docker-react"
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
