sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t iainlr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true iainlr/docker-react npm run test
  
